from __future__ import annotations

import os

from cryptography.fernet import Fernet

from vaultcli.crypto.key_derivation import derive_fernet_key


def encrypt_secret(plaintext: str, master_key: str, *, salt: bytes | None = None) -> str:
    """Encrypt secret data before sending it to any provider.

    Payload format: <salt_hex>$<fernet_token>
    """
    salt = salt or os.urandom(16)
    key = derive_fernet_key(master_key, salt)
    token = Fernet(key).encrypt(plaintext.encode("utf-8")).decode("utf-8")
    return f"{salt.hex()}${token}"


def decrypt_secret(encrypted_payload: str, master_key: str) -> str:
    """Decrypt payload generated by `encrypt_secret`."""
    salt_hex, token = encrypted_payload.split("$", 1)
    salt = bytes.fromhex(salt_hex)
    key = derive_fernet_key(master_key, salt)
    return Fernet(key).decrypt(token.encode("utf-8")).decode("utf-8")
